### ISSUE TITLE
CPU increase when adding LOKI URL

### ISSUE THREAD

**Issue by runelucica** [sipcapture/heplify-server#335] opened 2020-03-07 16:18 UTC
I found another strange CPU related issue. 
I am running a setup with 2 machines both running docker containers:

1. Machine 1 runs heplify-server, postgresql, homer-webapp and traefik containers
2. Machine 2 runs prometheus, prom alertmanager, prom node-exporter, grafana, loki and traefik containers

I added the LokiURL recently on the heplify-server configuration. After a couple of minutes I noticed that the heplify-server container is eating up the CPU. Looking at the heplify-server logs I noticed that it does not even show that it is trying to connect to the Loki URL. I have tried both the old and new Loki URL format (/api/prom/push and /loki/api/v1/push).

  PID USER      PR  NI    VIRT    RES    SHR S  **%CPU** %MEM     TIME+ COMMAND
15839 root      20   0  189908 126004   5976 S **450.5**  0.8  61:52.02 **heplify-server**
15446 root      20   0  109092  10160   3124 S   2.0  0.1   0:15.44 containerd-shim
 1867 root      20   0 1156508  52572  14932 S   1.0  0.3  76:18.03 containerd
 1887 root      20   0 1368812 115100  29948 S   1.0  0.7  54:23.61 dockerd

In contrast, when configuring a fake/non-working URL I can immediately see in the heplify-server logs the connection failure and of course the CPU stays within normal values.

I have a couple of questions:
- Does the heplify-server send real-time data to Loki or will it send data for traffic received in the past? I was thinking that since the heplify-server has been consuming data for some days prior to enabling Loki, it might try to send historical data for traffic received already.
- What would you recommend for troubleshooting this further?
- Could you please help with understanding what the other Loki specific heplify-server parameters do? Maybe I can improve this by adjusting some of them.
   HEPLIFYSERVER_LOKIBUFFER
   HEPLIFYSERVER_LOKIBULK
   HEPLIFYSERVER_LOKIHEPFILTER
   HEPLIFYSERVER_LOKITIMER

**Comment by negbie** [comment] 2020-03-08 18:52
There are just POST request to Loki so it makes no sense to log them if they are successful. I will only log failed requests to Loki.

To your questions:
Almost realtime but there are some buffers in place which handle some traffic spikes.
I need more informations. Which client do you use? How many packets do you send? Which heplify-server version do you use? I need the full heplify-server.log during the CPU increase (please mask sensitive data).
HEPLIFYSERVER_LOKIBUFFER is the buffered channel capacity to handle spikes, HEPLIFYSERVER_LOKIBULK batch size in Kilobytes, HEPLIFYSERVER_LOKIHEPFILTER will pass only HEP types in that filter, HEPLIFYSERVER_LOKITIMER timer in seconds to force send packets even if the batch size is lower than HEPLIFYSERVER_LOKIBULK.

Is the behaviour reproducible? I tested it with hammerhep https://github.com/negbie/hammerHEP/releases but can't reproduce it. Can you reproduce it with hammerhep?

**Comment by runelucica** [comment] 2020-03-08 20:25
Thank you for the explanations for the other parameters.
I am running heplify-server v1.19. 
I am sending captured traffic from heplify agents. There are 6 agents at the moment and the number of packets is low, while CPU is still at a high value:

![image](https://user-images.githubusercontent.com/41921868/76170490-a760c080-6182-11ea-94e6-d31c95d742f5.png)

However, I think my problem is related to my reverse-proxy settings for Loki.
I have tested this some more and noticed that even though Grafana was reporting that it can connect locally to Loki (containers on the same VM), Loki was not working correctly from the other machine. The Loki site appeared to be working remotely, but something was not right. 
I changed some things on the reverse-proxy and tested again with debug logging on heplify-server.
This time around all worked OK. 

I believe we can close this one.

Many thanks again for the help and extra explanations. It is very much appreciated!

**Comment by negbie** [comment] 2020-03-08 20:35
Would it help you to include Loki POST request in the debug log?

**Comment by runelucica** [comment] 2020-03-09 09:21
OK. So I started testing again this morning trying to revert the setup to the non-working one.
I noticed something strange. The heplify-server is again expecting TLS connections. 
Here is the heplify-server configuration:

  heplify-server:
    image: sipcapture/heplify-server:master
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
      - "9096:9096"
    command:
      - './heplify-server'
    environment:
      **- "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTLSADDR="
      - "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9060"**
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBADDR=db:5432"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_DBCONFTABLE=homer_config"
      - "HEPLIFYSERVER_DBDROPDAYS=30"
      - "HEPLIFYSERVER_LOGDBG=hep,sql"
      - "HEPLIFYSERVER_LOGLVL=debug"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_DEDUP=false"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
**#      - "HEPLIFYSERVER_LOKIURL=http://vm2-ip:3100/loki/api/v1/push"**
**#      - "HEPLIFYSERVER_LOKITIMER=2"**
    restart: unless-stopped
    depends_on:
      - db
    labels:
      org.label-schema.group: "monitoring"

This is an extract from the heplify-server log:

> heplify-server           | Could not find toml config file, use flag defaults. <nil>
heplify-server           | 2020/03/09 08:50:06.058237 server.go:83: INFO start heplify-server 1.19 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"0.0.0.0:9060", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"", LokiBulk:400, LokiTimer:4, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"db:5432", DBUser:"****", DBPass:"****", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:30, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_domain", "to_user", "callid", "method", "user_agent"}, LogDbg:"hep,sql", LogLvl:"debug", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
heplify-server           | 2020/03/09 08:50:06.058446 prometheus.go:38: INFO expose metrics without or unbalanced targets
heplify-server           | 2020/03/09 08:50:06.058806 tcp.go:25: ERR listen tcp 0.0.0.0:9060: bind: address already in use
heplify-server           | 2020/03/09 08:50:08.063016 rotator.go:394: WARN pq: database "homer_data" already exists
heplify-server           |
heplify-server           | 2020/03/09 08:50:08.063262 rotator.go:394: WARN pq: role "homer_user" already exists
heplify-server           |
heplify-server           | 2020/03/09 08:50:08.063478 rotator.go:394: WARN pq: role "postgres" does not exist
heplify-server           |
heplify-server           | 2020/03/09 08:50:08.064756 rotator.go:332: INFO start creating tables (2020-03-09 08:50:08.064723577 +0000 UTC m=+2.018535633)
heplify-server           | 2020/03/09 08:50:08.258497 rotator.go:345: INFO end creating tables (2020-03-09 08:50:08.258487629 +0000 UTC m=+2.212299586)
heplify-server           | 2020/03/09 08:50:08.260902 postgres.go:61: INFO postgres connection established
heplify-server           | 2020/03/09 08:50:12.936094 tls.go:53: INFO new TLS connection heplify-agent-1:54890 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:50:12.936259 tls.go:64: INFO closing TLS connection from heplify-agent-1:54890
heplify-server           | 2020/03/09 08:50:23.133751 tls.go:53: INFO new TLS connection heplify-agent-2:59664 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:50:23.133843 tls.go:64: INFO closing TLS connection from heplify-agent-2:59664
heplify-server           | 2020/03/09 08:50:50.717646 tls.go:53: INFO new TLS connection heplify-agent-3:54554 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:50:51.914249 tls.go:53: INFO new TLS connection heplify-agent-4:58020 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:50:51.914445 tls.go:64: INFO closing TLS connection from heplify-agent-4:58020
heplify-server           | 2020/03/09 08:50:59.205251 tls.go:53: INFO new TLS connection heplify-agent-2:59668 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:50:59.205374 tls.go:64: INFO closing TLS connection from heplify-agent-2:59668
heplify-server           | 2020/03/09 08:51:13.636723 tls.go:53: INFO new TLS connection heplify-agent-5:42768 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:51:39.285435 tls.go:53: INFO new TLS connection heplify-agent-2:59670 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:51:41.316085 tls.go:53: INFO new TLS connection heplify-agent-6:44566 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:52:02.052710 tls.go:53: INFO new TLS connection heplify-agent-4:58024 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 08:52:02.153250 tls.go:53: INFO new TLS connection heplify-agent-1:54896 -> heplify-server-docker-internal-IP:9060

I am afraid this might not have been related to the Loki URL configuration after all.
I have tried commenting out the "HEPLIFYSERVER_HEPTLSADDR=" parameter, however I can still see TLS connection attempts.

I have tried again, commenting out the UDP HEP address. This time I can see heplify-server accepting TCP connections.

I stopped again and added all configuration parameters again (including the LOKIURL) and I see again TLS connections.

Am I doing something wrong with how I provide the heplify-server environment variables?
This is the current configuration generating high CPU usage:

>   heplify-server:
    image: sipcapture/heplify-server:master
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
      - "9096:9096"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTLSADDR="
      - "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBADDR=db:5432"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_DBCONFTABLE=homer_config"
      - "HEPLIFYSERVER_DBDROPDAYS=30"
      - "HEPLIFYSERVER_LOGDBG=hep,sql,loki"
      - "HEPLIFYSERVER_LOGLVL=debug"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_DEDUP=false"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_LOKIURL=http://172.19.160.144:3100/loki/api/v1/push"
      - "HEPLIFYSERVER_LOKITIMER=2"
    restart: unless-stopped
    depends_on:
      - db
    labels:
      org.label-schema.group: "monitoring"

Since this is not related to Loki after all I am ok with either renaming the issue or continuing the tshoot on [https://github.com/sipcapture/heplify-server/issues/331](url)

**Comment by negbie** [comment] 2020-03-09 09:37
I see from your log heplify-server | 2020/03/09 08:50:06.058806 tcp.go:25: ERR listen tcp 0.0.0.0:9060: bind: address already in use

Whats listening on 9060 tcp already?

**Comment by negbie** [comment] 2020-03-09 09:39
"I have tried commenting out the "HEPLIFYSERVER_HEPTLSADDR=" parameter, however I can still see TLS connection attempts."
TLS connections attempts are initiated from clients. I'm not sure I can follow you.

**Comment by runelucica** [comment] 2020-03-09 10:27
**What is listening on port TCP 9060?**
- with the docker images running only heplify-server

**docker ps**
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                   PORTS                                                                    NAMES
d083cd12223e        sipcapture/heplify-server:master   "./heplify-server"       5 minutes ago       Up 5 minutes             0.0.0.0:9060->9060/tcp, 0.0.0.0:9096->9096/tcp, 0.0.0.0:9060->9060/udp   heplify-server
9ad562b456dc        sipcapture/webapp                  "/docker-entrypoint.…"   4 days ago          Up 4 minutes                                                                                      homer-webapp
5b654d345b5f        traefik:v2.1                       "/entrypoint.sh --ac…"   4 days ago          Up 5 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8080->8080/tcp         hep-postgre-homer-app_traefik-reverse-proxy_1
17d21e7eec83        postgres:11-alpine                 "docker-entrypoint.s…"   4 days ago          Up 5 minutes (healthy)   5432/tcp                                                                 db


**netstat -nlp | grep 9060**
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::9060                 :::*                    LISTEN      24285/docker-proxy
udp6       0      0 :::9060                 :::*                                24304/docker-proxy

- with no docker images running, nothing.

**docker-compose -f /opt/hep-postgre-homer-app/docker-compose.yml stop**
Stopping heplify-server                                ... done
Stopping homer-webapp                                  ... done
Stopping hep-postgre-homer-app_traefik-reverse-proxy_1 ... done
Stopping db                                            ... done

**docker ps**
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**netstat -nlp | grep 9060**

TLS Connection Attempts
- what I meant is that the heplify-server is assuming that the connection attempts on port TCP 9060 are TLS connections; the heplify agents are attempting TCP connections 

I stopped and started again the docker-compose containing the heplify-server service using the same config as above.
This time around heplify-server is expecting TCP instead TLS connections.

This is an extract from the heplify-server log:

> heplify-server           | 2020/03/09 09:28:24.333256 server.go:83: INFO start heplify-server 1.19 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"0.0.0.0:9060", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"http://vm2-IP:3100/loki/api/v1/push", LokiBulk:400, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"db:5432", DBUser:"root", DBPass:"homerSeven", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:30, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_domain", "to_user", "callid", "method", "user_agent"}, LogDbg:"hep,sql,loki", LogLvl:"debug", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
heplify-server           | 2020/03/09 09:28:24.334151 prometheus.go:38: INFO expose metrics without or unbalanced targets
heplify-server           | 2020/03/09 09:28:24.334160 **tls.go**:25: ERR listen tcp 0.0.0.0:9060: bind: address already in use
heplify-server           | 2020/03/09 09:28:26.345207 rotator.go:394: WARN pq: database "homer_data" already exists
heplify-server           |
heplify-server           | 2020/03/09 09:28:26.345370 rotator.go:394: WARN pq: role "homer_user" already exists
heplify-server           |
heplify-server           | 2020/03/09 09:28:26.345482 rotator.go:394: WARN pq: role "postgres" does not exist
heplify-server           |
heplify-server           | 2020/03/09 09:28:26.346291 rotator.go:332: INFO start creating tables (2020-03-09 09:28:26.346279482 +0000 UTC m=+2.021567954)
heplify-server           | 2020/03/09 09:28:26.563357 rotator.go:345: INFO end creating tables (2020-03-09 09:28:26.563347756 +0000 UTC m=+2.238636272)
heplify-server           | 2020/03/09 09:28:26.566017 postgres.go:61: INFO postgres connection established
heplify-server           | 2020/03/09 09:29:03.752242 **tcp.go**:47: INFO new TCP connection heplify-agent:59776 -> heplify-server-docker-internal-IP:9060

This is what I noticed different in the heplify server logs when TLS is attempted, even though the configured setting is TCP:

heplify-server | 2020/03/09 08:50:06.058806 **tcp.go**:25: ERR listen tcp 0.0.0.0:9060: bind: address already in use
After this I see logs similar to:
heplify-server | 2020/03/09 08:50:23.133751 **tls.go**:53: INFO **new TLS** connection heplify-agent-2:59664 -> heplify-server-docker-internal-IP:9060
heplify-server | 2020/03/09 08:50:23.133843 **tls.go**:64: INFO **closing TLS** connection from heplify-agent-2:59664

In contrast when heplify-server expects TCP (when it is configured for TCP) I can see in the logs:

heplify-server           | 2020/03/09 09:31:33.847951 server.go:83: INFO start heplify-server 1.19 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"0.0.0.0:9060", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"http://vm2-IP:3100/loki/api/v1/push", LokiBulk:400, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"db:5432", DBUser:"root", DBPass:"homerSeven", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:30, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_domain", "to_user", "callid", "method", "user_agent"}, LogDbg:"hep,sql,loki", LogLvl:"debug", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
heplify-server           | 2020/03/09 09:31:33.848165 prometheus.go:38: INFO expose metrics without or unbalanced targets
heplify-server           | 2020/03/09 09:31:33.849802 **tls.go**:25: ERR listen tcp 0.0.0.0:9060: bind: address already in use

After this I can see TCP connection established from the heplify agents:
heplify-server           | 2020/03/09 09:34:23.388449 **tcp.go**:47: INFO new TCP connection heplify-agent-1:59792 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 09:34:35.134012 **tcp.go**:47: INFO new TCP connection heplify-agent-2:58130 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 09:34:44.458554 **tcp.go**:47: INFO new TCP connection heplify-agent-3:44660 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 09:34:45.834485 **tcp.go**:47: INFO new TCP connection heplify-agent-4:42866 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 09:34:53.977131 **tcp.go**:47: INFO new TCP connection heplify-agent-5:54686 -> heplify-server-docker-internal-IP:9060
heplify-server           | 2020/03/09 09:35:46.375874 **tcp.go**:47: INFO new TCP connection heplify-agent-6:55008 -> heplify-server-docker-internal-IP:9060

After stopping the heplify-server container:
heplify-server           | 2020/03/09 09:44:56.173549 **tcp.go**:58: INFO closing TCP connection from heplify-agent-5:54686
heplify-server           | 2020/03/09 09:44:56.371416 **tcp.go**:58: INFO closing TCP connection from heplify-agent-2:58130
heplify-server           | 2020/03/09 09:44:56.455721 **tcp.go**:58: INFO closing TCP connection from heplify-agent-6:55008
heplify-server           | 2020/03/09 09:44:56.644631 **tcp.go**:58: INFO closing TCP connection from heplify-agent-1:59792
heplify-server           | 2020/03/09 09:44:56.672509 **tcp.go**:58: INFO closing TCP connection from heplify-agent-3:44660
heplify-server           | 2020/03/09 09:44:57.041714 **tcp.go**:58: INFO closing TCP connection from heplify-agent-4:42866

I stopped all containers again, waited a couple of minutes and started everything. Everything works OK (TCP connections, not TLS).

I can't figure out why without changing the configuration, sometimes the heplify-server logs show TLS connection attempts instead of TCP.

Let me know what other logs, debugs or tests would help troubleshoot this further.

**Comment by negbie** [comment] 2020-03-09 11:31
Thanks for the details. Well maybe the log text can be improved because TLS connections are always over TCP.

"what I meant is that the heplify-server is assuming that the connection attempts on port TCP 9060 are TLS connections; the heplify agents are attempting TCP connections"

So you use heplify with the -nt flag like
./heplify -nt tcp -hs ......

Could you please do a docker-compose pull and restart the containers so that you have the latest heplify-server versions?

**Comment by negbie** [comment] 2020-03-09 11:39
Something else I've noticed in your config:

HEPAddr:"0.0.0.0:9060"
HEPTCPAddr:"0.0.0.0:9060"
HEPTLSAddr:"0.0.0.0:9060"

You cannot do that! While it's totally fine to listen UDP and TCP on the same port you normally can't do it the way you configured it. Keep in mind TLS is over TCP too.

So HEPTCPAddr and HEPTLSAddr should be on a different port like:

HEPAddr:"0.0.0.0:9060"
HEPTCPAddr:"0.0.0.0:9060"
HEPTLSAddr:"0.0.0.0:9061"

**Comment by runelucica** [comment] 2020-03-09 12:13
**All the heplify agents are configured like this:**
/opt/heplify/heplify -i ens224 -hs heplify-server-IP:9060 -nt tcp -m SIPRTCP -hi 11101 -hn heplify-agent-name

**With regards to the heplify-server config, I have configured TCP or TLS, never both:**
environment:
- "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
- "HEPLIFYSERVER_HEPTLSADDR="
- "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9060"

**OR** 

environment:
- "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
- "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
- "HEPLIFYSERVER_HEPTCPADDR="

Regardless whether I specify TCP or TLS in the heplify-server logs I can see all options configured with the same value:

heplify-server | 2020/03/09 09:28:24.333256 server.go:83: INFO start heplify-server 1.19 with config.HeplifyServer{**HEPAddr**:"0.0.0.0:9060", **HEPTCPAddr**:"0.0.0.0:9060", **HEPTLSAddr**:"0.0.0.0:9060"

If I don't specify any values in the docker-compose environment variables does the heplify-server apply some default values?

I will pull the latest images, test again and provide the test results.

Thanks again for the help!

**Comment by negbie** [comment] 2020-03-09 12:31
Ah sorry and thanks for the clarification. Now I get your point. Yes there are some default values and I was able to reproduce the double bind:

      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
        #- "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:1234"
      - "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9060"

Will result in 
HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"0.0.0.0:9060", HEPTLSAddr:"0.0.0.0:9060"

You can find all default values here:
https://github.com/sipcapture/heplify-server/blob/master/config/config.go

So if you don't want to expose TLS listener you can use as a workaround:
 - "HEPLIFYSERVER_HEPTLSADDR=-"

I will address this soon.

**Comment by runelucica** [comment] 2020-03-09 12:43
Awesome :).
Will either use this or configure different ports to make sure there will be no double bind.
Do you still want me to test or we are good for now?

**Comment by runelucica** [comment] 2020-03-09 13:08
Pulled the latest images. All good so far.
Also noticed the addition of loki.go (LOGDBG=loki) logs for PUSH requests. Works like a charm :).

If you also agree we can close this one.

**Comment by negbie** [comment] 2020-03-09 13:16
@runelucica thank you very much to help me out with testing! Yes if you want you can close this here. I will remove the default value for the TLS address. Yes I added some debug for loki POST request and log their response. So since the problem with double bind and Loki is solved I would like to find the root cause for your high CPU usage.

I tested it with
./hammerhep -transport udp -rate 1000
./hammerhep -transport udp,tls -rate 1000
./hammerhep -transport tcp -rate 1000
./hammerhep -transport udp,tcp -rate 1000
./hammerhep -transport tls -rate 1000

but couldn't reproduce. Anyway let's move to the other issue ;)

**Closed** 2020-03-09 13:24 UTC
