### ISSUE TITLE
heplify method response {response} contains symbols

### ISSUE THREAD

**Issue by PNRxA** [sipcapture/heplify-server#68] opened 2018-05-30 01:34 UTC
Hi, I'm using Heplify-Server to expose Prometheus metrics. I'm using the Heplify capture agent on a 3CX server to send data to Heplify-Server.

Some of the heplify_method_response metrics seem to have interesting responses like JSip0NOTIFY and Sip0CANCEL, is this normal?

Here are all the heplify_method_response metrics being exposed

`heplify_method_response{method="ACK",response="ACK",target_name="3cx"} 284
heplify_method_response{method="ACK",response="Sip0ACK",target_name="3cx"} 2
heplify_method_response{method="BYE",response="200",target_name="3cx"} 6
heplify_method_response{method="BYE",response="BYE",target_name="3cx"} 6
heplify_method_response{method="BYE",response="Sip0BYE",target_name="3cx"} 1
heplify_method_response{method="CANCEL",response="Sip0CANCEL",target_name="3cx"} 2
heplify_method_response{method="CANCEL",response="200",target_name="3cx"} 2
heplify_method_response{method="CANCEL",response="CANCEL",target_name="3cx"} 2
heplify_method_response{method="INFO",response="200",target_name="3cx"} 930
heplify_method_response{method="INFO",response="INFO",target_name="3cx"} 930
heplify_method_response{method="INVITE",response="\nSip0INVITE",target_name="3cx"} 2
heplify_method_response{method="INVITE",response="100",target_name="3cx"} 282
heplify_method_response{method="INVITE",response="180",target_name="3cx"} 7
heplify_method_response{method="INVITE",response="200",target_name="3cx"} 182
heplify_method_response{method="INVITE",response="401",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="407",target_name="3cx"} 12
heplify_method_response{method="INVITE",response="415",target_name="3cx"} 97
heplify_method_response{method="INVITE",response="487",target_name="3cx"} 2
heplify_method_response{method="INVITE",response="INVITE",target_name="3cx"} 325
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="NOTIFY",response="JSip0NOTIFY",target_name="3cx"} 2
heplify_method_response{method="NOTIFY",response="NSip0NOTIFY",target_name="3cx"} 2
heplify_method_response{method="NOTIFY",response="PSip0NOTIFY",target_name="3cx"} 2
heplify_method_response{method="NOTIFY",response="200",target_name="3cx"} 951
heplify_method_response{method="NOTIFY",response="406",target_name="3cx"} 386
heplify_method_response{method="NOTIFY",response="500",target_name="3cx"} 4
heplify_method_response{method="NOTIFY",response="NOTIFY",target_name="3cx"} 1338
heplify_method_response{method="OPTIONS",response="OPTIONS",target_name="3cx"} 1
heplify_method_response{method="REGISTER",response="200",target_name="3cx"} 927
heplify_method_response{method="REGISTER",response="401",target_name="3cx"} 22
heplify_method_response{method="REGISTER",response="407",target_name="3cx"} 883
heplify_method_response{method="REGISTER",response="REGISTER",target_name="3cx"} 1832
heplify_method_response{method="REGISTER",response="Sip0REGISTER",target_name="3cx"} 405
heplify_method_response{method="SUBSCRIBE",response="200",target_name="3cx"} 743
heplify_method_response{method="SUBSCRIBE",response="407",target_name="3cx"} 101
heplify_method_response{method="SUBSCRIBE",response="SUBSCRIBE",target_name="3cx"} 844
heplify_method_response{method="SUBSCRIBE",response="Sip0SUBSCRIBE",target_name="3cx"} 12`

**Comment by negbie** [comment] 2018-05-30 05:15
Hi, I can only imagine that this could happen during startup phase of heplify-server while heplify is already running. The counters stay the same now for those right?

**Comment by PNRxA** [comment] 2018-05-30 05:18
Both the agent and server have been running since I opened the issue, here is the current numbers

`
heplify_method_response{method="ACK",response="Sip0ACK",target_name="3cx"} 1
heplify_method_response{method="ACK",response="Sip0ACK",target_name="3cx"} 2
heplify_method_response{method="ACK",response="\"�MSC0��'��}��������������USip0ACK",target_name="3cx"} 1
heplify_method_response{method="ACK",response="\"�MSC0��'_������sendrec�5\"�MSC0��']���������������\"�MSC0������[����������������\"�MSC0�����Y�������3",target_name="3cx"} 1
heplify_method_response{method="ACK",response="ACK",target_name="3cx"} 1023
heplify_method_response{method="ACK",response="Sip0ACK",target_name="3cx"} 12
heplify_method_response{method="BYE",response="Sip0BYE",target_name="3cx"} 1
heplify_method_response{method="BYE",response="Sip0BYE",target_name="3cx"} 2
heplify_method_response{method="BYE",response="/Sip0BYE",target_name="3cx"} 3
heplify_method_response{method="BYE",response="200",target_name="3cx"} 33
heplify_method_response{method="BYE",response="BYE",target_name="3cx"} 33
heplify_method_response{method="BYE",response="Sip0BYE",target_name="3cx"} 2
heplify_method_response{method="CANCEL",response="Sip0CANCEL",target_name="3cx"} 2
heplify_method_response{method="CANCEL",response="\nSip0CANCEL",target_name="3cx"} 4
heplify_method_response{method="CANCEL",response="Sip0CANCEL",target_name="3cx"} 3
heplify_method_response{method="CANCEL",response="200",target_name="3cx"} 16
heplify_method_response{method="CANCEL",response="CANCEL",target_name="3cx"} 16
heplify_method_response{method="INFO",response="200",target_name="3cx"} 3192
heplify_method_response{method="INFO",response="INFO",target_name="3cx"} 3192
heplify_method_response{method="INFO",response="Sip0INFO",target_name="3cx"} 3
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="1Sip0INVITE",target_name="3cx"} 2
heplify_method_response{method="INVITE",response=";Sip0INVITE",target_name="3cx"} 4
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="\nSip0INVITE",target_name="3cx"} 3
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="\"�MSC0��'/y�������",target_name="3cx"} 1
heplify_method_response{method="INVITE",response="100",target_name="3cx"} 980
heplify_method_response{method="INVITE",response="180",target_name="3cx"} 44
heplify_method_response{method="INVITE",response="183",target_name="3cx"} 5
heplify_method_response{method="INVITE",response="200",target_name="3cx"} 624
heplify_method_response{method="INVITE",response="401",target_name="3cx"} 10
heplify_method_response{method="INVITE",response="404",target_name="3cx"} 27
heplify_method_response{method="INVITE",response="407",target_name="3cx"} 41
heplify_method_response{method="INVITE",response="415",target_name="3cx"} 327
heplify_method_response{method="INVITE",response="487",target_name="3cx"} 16
heplify_method_response{method="INVITE",response="INVITE",target_name="3cx"} 1140
heplify_method_response{method="INVITE",response="Sip0INVITE",target_name="3cx"} 6
heplify_method_response{method="MESSAGE",response="Sip0MESSAGE",target_name="3cx"} 5
heplify_method_response{method="NOTIFY",response="\nSip0NOTIFY",target_name="3cx"} 1
heplify_method_response{method="NOTIFY",response="Sip0NOTIFY",target_name="3cx"} 3
heplify_method_response{method="NOTIFY",response="JSip0NOTIFY",target_name="3cx"} 5
heplify_method_response{method="NOTIFY",response="NSip0NOTIFY",target_name="3cx"} 8
heplify_method_response{method="NOTIFY",response="OSip0NOTIFY",target_name="3cx"} 2
heplify_method_response{method="NOTIFY",response="PSip0NOTIFY",target_name="3cx"} 5
heplify_method_response{method="NOTIFY",response="200",target_name="3cx"} 3592
heplify_method_response{method="NOTIFY",response="406",target_name="3cx"} 1299
heplify_method_response{method="NOTIFY",response="500",target_name="3cx"} 27
heplify_method_response{method="NOTIFY",response="NOTIFY",target_name="3cx"} 4892
heplify_method_response{method="OPTIONS",response="OPTIONS",target_name="3cx"} 11
heplify_method_response{method="REGISTER",response="Sip0REGISTER",target_name="3cx"} 2
heplify_method_response{method="REGISTER",response="Sip0REGISTER",target_name="3cx"} 1
heplify_method_response{method="REGISTER",response="!Sip0REGISTER",target_name="3cx"} 2
heplify_method_response{method="REGISTER",response="*Sip0REGISTER",target_name="3cx"} 2
heplify_method_response{method="REGISTER",response="200",target_name="3cx"} 3119
heplify_method_response{method="REGISTER",response="401",target_name="3cx"} 73
heplify_method_response{method="REGISTER",response="407",target_name="3cx"} 2974
heplify_method_response{method="REGISTER",response="7Sip0REGISTER",target_name="3cx"} 1
heplify_method_response{method="REGISTER",response=":Sip0REGISTER",target_name="3cx"} 1
heplify_method_response{method="REGISTER",response="REGISTER",target_name="3cx"} 6166
heplify_method_response{method="REGISTER",response="Sip0REGISTER",target_name="3cx"} 1368
heplify_method_response{method="SUBSCRIBE",response="200",target_name="3cx"} 2479
heplify_method_response{method="SUBSCRIBE",response="407",target_name="3cx"} 344
heplify_method_response{method="SUBSCRIBE",response="SUBSCRIBE",target_name="3cx"} 2823
heplify_method_response{method="SUBSCRIBE",response="Sip0SUBSCRIBE",target_name="3cx"} 40`

**Comment by PNRxA** [comment] 2018-05-30 05:37
Traffic isn't high as I'm just trying out the one agent to begin with before deploying it to other servers

I assume just run with log level "debug"? I'll do that and get back to you

**Comment by negbie** [comment] 2018-05-30 05:39
Exactly. I just tried to reproduce it but till now without success. To fix this I can simply check for valid responses but first I would like to geht the root cause

**Comment by negbie** [comment] 2018-05-30 05:42
It would be interesting to see if you have any of those malformed responses in the debug log

**Comment by PNRxA** [comment] 2018-05-30 05:51
Got something

heplify_method_response{method="NOTIFY",response="OSip0NOTIFY",target_name="puxv"} 1

in debug log

`2018-05-30T05:41:39Z DBG  [hep] &HEP{Version:2,Protocol:6,SrcIP:XXX.XXX.XXX.XXX,DstIP:XXX.XXX.XXX.XXX,SrcPort:5090,DstPort:49957,Tsec:1527658875,Tmsec:786858,ProtoType:1,NodeID:2002,NodePW:myhep,Payload:OSip0NOTIFY sip:104@XXX.XXX.XXX.XXX:50195;transport=TCP;rinstance=1-3cb2c261a90944d4ab5be61f9a31cb42;ob SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5060;branch=z9hG4bK-524287-1---4741ca12ee560001;rport=5060
Max-Forwards: 69
Contact: <sip:104@127.0.0.1:5060>
To: "EMPLOYEE NAME"<sip:104@SERVER.URL>;tag=4fcf3c4605824a93873db7a4093a60cd
From: "EMPLOYEE NAME"<sip:104@SERVER.URL>;tag=df36c666
Call-ID: 06930488a1f3424193dab93e374d5614
CSeq: 4 NOTIFY
Content-Type: application/simple-message-summary
User-Agent: 3CXPhoneSystem 15.5.10244.4 (10244)
Subscription-State: active;expires=3600
Event: message-summary
Content-Length: 42`


` 06930488a1f3424193dab93e374d5614 2018-05-30 05:41:15.786858 [123 34 112 114 111 116 111 99 111 108 70 97 109 105 108 121 34 58 50 44 34 112 114 111 116 111 99 111 108 34 58 54 44 34 115 114 99 73 112 34 58 34 49 55 50 46 51 49 46 50 55 46 51 50 34 44 34 100 115 116 73 112 34 58 34 50 50 48 46 50 52 52 46 57 54 46 49 52 34 44 34 115 114 99 80 111 114 116 34 58 53 48 57 48 44 34 100 115 116 80 111 114 116 34 58 52 57 57 53 55 44 34 116 105 109 101 83 101 99 111 110 100 115 34 58 49 53 50 55 54 53 56 56 55 53 44 34 116 105 109 101 85 115 101 99 111 110 100 115 34 58 55 56 54 56 53 56 44 34 112 97 121 108 111 97 100 84 121 112 101 34 58 49 44 34 99 97 112 116 117 114 101 73 100 34 58 50 48 48 50 44 34 99 97 112 116 117 114 101 80 97 115 115 34 58 34 109 121 104 101 112 34 125] [123 34 99 114 101 97 116 101 95 100 97 116 101 34 58 34 50 48 49 56 45 48 53 45 51 48 32 48 53 58 52 49 58 49 53 46 55 56 54 56 53 56 34 44 34 114 117 114 105 95 117 115 101 114 34 58 34 49 48 52 34 44 34 102 114 111 109 95 117 115 101 114 34 58 34 49 48 52 34 44 34 116 111 95 117 115 101 114 34 58 34 49 48 52 34 44 34 112 105 100 95 117 115 101 114 34 58 34 34 44 34 97 117 116 104 95 117 115 101 114 34 58 34 34 44 34 115 105 100 34 58 34 48 54 57 51 48 52 56 56 97 49 102 51 52 50 52 49 57 51 100 97 98 57 51 101 51 55 52 100 53 54 49 52 34 44 34 109 101 116 104 111 100 34 58 34 2 79 83 105 112 48 78 79 84 73 70 89 34 44 34 115 111 117 114 99 101 95 105 112 34 58 34 49 55 50 46 51 49 46 50 55 46 51 50 34 44 34 100 101 115 116 105 110 97 116 105 111 110 95 105 112 34 58 34 50 50 48 46 50 52 52 46 57 54 46 49 52 34 125] OSip0NOTIFY sip:104@XXX.XXX.XXX.XXX:50195;transport=TCP;rinstance=1-3cb2c261a90944d4ab5be61f9a31cb42;ob SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5060;branch=z9hG4bK-524287-1---4741ca12ee560001;rport=5060
Max-Forwards: 69
Contact: <sip:104@127.0.0.1:5060>
To: "EMPLOYEE NAME"<sip:104@SERVER.URL>;tag=4fcf3c4605824a93873db7a4093a60cd
From: "EMPLOYEE NAME"<sip:104@SERVER.URL>;tag=df36c666
Call-ID: 06930488a1f3424193dab93e374d5614
CSeq: 4 NOTIFY
Content-Type: application/simple-message-summary
User-Agent: 3CXPhoneSystem 15.5.10244.4 (10244)
Subscription-State: active;expires=3600
Event: message-summary
Content-Length: 42`

**Comment by negbie** [comment] 2018-05-30 05:59
Perfect! Thank you. So could you confirm this is only for TCP?

**Comment by negbie** [comment] 2018-05-30 06:05
Since I know the root cause. I will first implement a valid response check and have a look on TCP reassembling in heplify. Let me finish first some other work but I will publish a new heplify-server version in at least 3 hours.

**Comment by PNRxA** [comment] 2018-05-30 06:30
Good to hear, thanks for that. I can also confirm that the other ones which have popped up so far are TCP also

**Comment by negbie** [comment] 2018-05-30 08:39
New release is online. If you want to delete some Prometheus series, look under "Delete Series" here:
https://github.com/prometheus/prometheus/blob/master/docs/querying/api.md

**Comment by PNRxA** [comment] 2018-05-30 23:51
Thanks, I've cleared my series and everything is great. I guess the issue of the responses coming under unknown now is the responsibility of the agent used to provide valid data

**Comment by PNRxA** [comment] 2018-05-31 04:18
Just deployed it on a larger server, it's getting quite a lot of unknown responses and also one of the responses is not valid even with the new checking you added which is odd

**heplify_method_response{method="NOTIFY",response="..\"",target_name="NEWServer"} 1**



`heplify_method_response{method="ACK",response="ACK",target_name="NEWServer"} 43
heplify_method_response{method="ACK",response="UNKNOWN",target_name="NEWServer"} 339
heplify_method_response{method="BYE",response="200",target_name="NEWServer"} 16
heplify_method_response{method="BYE",response="BYE",target_name="NEWServer"} 16
heplify_method_response{method="BYE",response="UNKNOWN",target_name="NEWServer"} 48
heplify_method_response{method="CANCEL",response="UNKNOWN",target_name="NEWServer"} 18
heplify_method_response{method="INFO",response="200",target_name="NEWServer"} 100
heplify_method_response{method="INFO",response="INFO",target_name="NEWServer"} 100
heplify_method_response{method="INFO",response="UNKNOWN",target_name="NEWServer"} 1630
heplify_method_response{method="INVITE",response="100",target_name="NEWServer"} 44
heplify_method_response{method="INVITE",response="180",target_name="NEWServer"} 9
heplify_method_response{method="INVITE",response="183",target_name="NEWServer"} 5
heplify_method_response{method="INVITE",response="200",target_name="NEWServer"} 36
heplify_method_response{method="INVITE",response="401",target_name="NEWServer"} 7
heplify_method_response{method="INVITE",response="INVITE",target_name="NEWServer"} 44
heplify_method_response{method="INVITE",response="UNKNOWN",target_name="NEWServer"} 380
heplify_method_response{method="NOTIFY",response="..\"",target_name="NEWServer"} 1
heplify_method_response{method="NOTIFY",response="200",target_name="NEWServer"} 105
heplify_method_response{method="NOTIFY",response="500",target_name="NEWServer"} 1
heplify_method_response{method="NOTIFY",response="NOTIFY",target_name="NEWServer"} 151
heplify_method_response{method="NOTIFY",response="UNKNOWN",target_name="NEWServer"} 2342
heplify_method_response{method="OPTIONS",response="OPTIONS",target_name="NEWServer"} 1
heplify_method_response{method="REFER",response="UNKNOWN",target_name="NEWServer"} 7
heplify_method_response{method="REGISTER",response="200",target_name="NEWServer"} 106
heplify_method_response{method="REGISTER",response="401",target_name="NEWServer"} 3
heplify_method_response{method="REGISTER",response="407",target_name="NEWServer"} 100
heplify_method_response{method="REGISTER",response="REGISTER",target_name="NEWServer"} 216
heplify_method_response{method="REGISTER",response="UNKNOWN",target_name="NEWServer"} 3317
heplify_method_response{method="SUBSCRIBE",response="200",target_name="NEWServer"} 64
heplify_method_response{method="SUBSCRIBE",response="407",target_name="NEWServer"} 17
heplify_method_response{method="SUBSCRIBE",response="481",target_name="NEWServer"} 2
heplify_method_response{method="SUBSCRIBE",response="SUBSCRIBE",target_name="NEWServer"} 83
heplify_method_response{method="SUBSCRIBE",response="UNKNOWN",target_name="NEWServer"} 1354`

**Comment by negbie** [comment] 2018-05-31 07:59
Hi Peter,

> I guess the issue of responses coming under unknown is now the responsibility of the agent used to provide valid data

Yes I don't want to through away those invalid response so you can see that something strange is going on the capture agent side.

The first step was to add a basic response validator. The odd metrics you posted are valid in terms of my  validator
´´´
if h.SIP.StartLine.Method != h.SIP.CseqMethod && len(h.SIP.StartLine.Method) != 3 {
	h.SIP.StartLine.Method = "UNKNOWN"
}

to catch those I can try to cast them to int. I will benchmark this and if it does not decrease the performance I will add this too.

The next step is to look at heplify and TCP. I only tested heplify and tcp on small networks. All high traffic machines I have use UDP. In the mean time you have some options. You can try out if captagent handles your tcp traffic better. You can filter out the UNKNOWN responses in Grafana easily with response=~"[1-6].*"

**Comment by negbie** [comment] 2018-05-31 09:57
Hi Peter,

would it be possible to provide me in privat a pcap with some TCP traffic which results in some malformed responses? negbie@posteo.de

**Comment by PNRxA** [comment] 2018-05-31 23:39
Thanks, I'll try out the new version and see how it goes. Also, did you want a pcap of the heplify-server or heplify agent server?

Here's the difference after the update 

![image](https://user-images.githubusercontent.com/16978632/40813439-368dfc94-657e-11e8-85bf-035f6ca649f8.png)

**Comment by negbie** [comment] 2018-06-01 04:18
I would like to get the raw traffic so best on heplify side. The next step is to optimize the TCP capture code. Hmm looking at your latest image I ask myself why you have such high invite, register requests without a response.

**Comment by PNRxA** [comment] 2018-06-01 06:19
I'll work on getting a capture sent to your email which contains some unknown packets

Not too sure about the high invites/registers without responses...

**Comment by PNRxA** [comment] 2018-06-01 06:43
what tcpdump command do you want me to run for ideal output?

**Comment by negbie** [comment] 2018-06-01 06:50
Only with sip should be enough. portrange 5060-5090 if thats your sip portrange

**Comment by PNRxA** [comment] 2018-06-01 07:30
Something interesting, in wireshark after running

`tcpdump -nq -s 0 -i eth0 -w /tmp/dump.pcap 'tcp'`

The comments for SIP flow are things like 

```
3��Sip0INVITE
[��Sip0NOTIFY
A��Sip0SUBSCRIBE
etc
```


But when running 

tcpdump -nq -s 0 -i eth0 -w /tmp/dump.pcap port 5060

comments were

```
NOTIFY 200
SUBSCRIBE 407
SUBSCRIBE 407
etc
```

I'll try to send you through a pcap next week

**Comment by negbie** [comment] 2018-06-01 07:53
Ok thank you. As soon as I get them I will start to look into it. You captured this directly on the 3CX server right? So there are no port mirrors or something like that involved? In the first command you did not specify a port. Can you tell me which ports are used there?

**Comment by PNRxA** [comment] 2018-06-04 01:15
Sent you an email, seems like is a 3CX Tunnel / 3CX SBC thing as the ports are in that range...

https://www.3cx.com/docs/3cx-phone-system-v14-ports/

https://www.3cx.com/docs/3cx-tunnel-session-border-controller/

**Comment by negbie** [comment] 2018-06-04 04:14
Got it. Thank you. Will look into it today. Meanwhile you can run heplify with -pr 5060

**Comment by PNRxA** [comment] 2018-06-04 06:21
Thanks for looking into it, that means the traffic coming from behind the SBC/Tunnel won't be picked up by heplify right? Not that much can be done because they combine SIP and RTP and use a custom TCP protocol

**Comment by negbie** [comment] 2018-06-04 07:07
Yes, when you set -pr 5060 the tunnel traffic will be ignored. I think the most important aspect of a capture system is correctness so you can trust it. Due to the custom TCP protocol this is not the case anymore because its not supported by heplify. I can look into it and mby its easy to decode

**Comment by PNRxA** [comment] 2018-06-04 07:52
I agree - I've changed the agents I've got running to 5060 for the time being to see how it goes, no unknown traffic so far

I hesitated as I won't see much traffic from one of our big servers which has all their phones behind SBCs. For the other servers it means I won't be able to see traffic from the windows clients which some use exclusively 

I appreciate any time you take to look into the custom protocol but understand if it's too much of a pain - it might not be worth supporting as it's a unique problem

**Comment by negbie** [comment] 2018-06-04 08:16
The problem by looking at the pcap trace is that there are only SIP requests and no responses. I don't know how they transmit them and sadly there is no documentation available. Do they send the responses over another port? I think the validator inside heplify-server would detect and correct most of the SIP messages which goes over that tunnel but without SIP responses this makes no sense and will invalidate all the usefull KPI's.

**Comment by PNRxA** [comment] 2018-06-04 23:31
I'll have a bit of a look into it and see what I can find, if I find some more interesting packets I might send you through another pcap trace

**Comment by PNRxA** [comment] 2018-06-05 00:28
Alright it looks like there are responses but they aren't interpreted by wireshark so it doesn't show it and also didn't export it when I sent you the pcap earlier. I was able to open the pcap in a text editor and can see that under each sip0message packet from the tunnel there is a response somewhere 

I'll send you another email with the full pcap

**Comment by negbie** [comment] 2018-06-05 06:50
Thank you. I guess thats something I can work with. Give me some hours to decode that and I will send you a special heplify version via mail.

**Comment by PNRxA** [comment] 2018-06-05 07:33
Thanks a lot, I appreciate it. Let me know if you need any more info

**Comment by negbie** [comment] 2018-06-05 08:46
I've sent you a modified heplify version which is able to decode this tunnel. Please test it. Best would be to see if homer can display the whole flow. So don't test only the metrics but also the whole flow.

You can test some of your pcap's with:
./heplify -rf test.pcap -e -d payload

I couldn't test IPv6 over that tunnel because it seems you have no IPv6 traffic but it should work too.

**Comment by PNRxA** [comment] 2018-06-05 08:50
I'll be sure to test it tomorrow and report back

About the homer front end, does running heplify-server have a front end or is it a separate server application?

I run a homer5 server but had issues so am currently not using it, couldn't find any documentation on the homer7 web app

**Comment by negbie** [comment] 2018-06-05 08:53
heplify-server is a kamailio and rotation script replacement. You can use heplify-server with homer5. What issues do you have? Are the homer5 php,js files in place and do you have a running apache or nginx? How can I help?

**Comment by PNRxA** [comment] 2018-06-05 09:05
I have an open issue with homer which describes the problems I'm having with it, basically I can only see the call flows for like 4 minutes (e.g 10am - 10:04am) every day and it's spitting out database errors about row length

That's with captagent however, it might work alright with the custom heplify, I'll give it a shot in the morning

I might ditch the server and start a homer5 instance on the heplify-server. Does it still need kamailio in that case? I just used the quick and dirty installer to get it running previously but I can give the manual installation a shot

**Comment by negbie** [comment] 2018-06-05 09:08
Try to use the new modified heplify version and heplify-server on that server. When you don't need kamailio config language and simply want a capture solution don't use kamailio anymroe.

**Comment by negbie** [comment] 2018-06-05 09:10
You simply put heplify-server in place of kamailio. Just configure heplify-server with the db credentials and the other stuff you need. Don't forget to disable the rotation cronjob.

**Comment by negbie** [comment] 2018-06-05 09:40
If you need help with the setup of homer frontend + heplify-server just open a new issue for heplify-server and I will guide you through. Even if you want install it manually its not that hard anymore.

**Comment by PNRxA** [comment] 2018-06-06 05:54
I'm testing the new agent out, haven't got the homer front end up yet as I'm getting database access errors - I'll launch a ticket after trying again tomorrow

Here's the metrics change

![image](https://user-images.githubusercontent.com/16978632/41019355-98313390-69a1-11e8-89ed-9ea475d984a6.png)

Seems way more stable

**Comment by negbie** [comment] 2018-06-06 05:59
Yeah this looks better

**Comment by negbie** [comment] 2018-06-06 06:15
I will close this here since its related to heplify not heplify-server.

**Closed** 2018-06-06 06:15 UTC

**Comment by PNRxA** [comment] 2018-06-06 06:17
Just in case they might be of interest, here are some warnings in the logs

```
2018-06-06T15:43:07+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly

2018-06-06T15:45:33+10:00 WARN Could not find a valid CSeq in packet

2018-06-06T15:45:54+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLine err: length of s.Val is less than 3. Invalid start line
```

Here are some examples of the above

**2018-06-06T15:43:07+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly**

```
2018-06-06T15:42:43+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"d38;rport=5060\r\nContact: <sip:136@XXX.XXX.XXX.XXX:5060>\r\nTo: \"EMPLOYEE NAME\" <sip:136@SERVER.URL.COM:5060>;tag=2865600169\r\nFrom: <sip:SP1@SERVER.URL.COM:5060>;tag=b2681554\r\nCall-ID: 0_3107511855@XXX.XXX.XXX.XXX\r\nCSeq: 119 NOTIFY\r\nUser-Agent: Yealink SIP-T46S XXX.XXX.XXX.XXX 001565ca0412\r\nContent-Length: 0\r\n\r\n"

2018-06-06T15:43:07+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"38;rport=5060\r\nContact: <sip:197@XXX.XXX.XXX.XXX:5060>\r\nTo: \"EMPLOYEE NAME\" <sip:197@SERVER.URL.COM:5060>;tag=2340671879\r\nFrom: <sip:SP1@SERVER.URL.COM:5060>;tag=5282b10e\r\nCall-ID: 0_1003122249@XXX.XXX.XXX.XXX\r\nCSeq: 121 NOTIFY\r\nUser-Agent: Yealink SIP-T46S XXX.XXX.XXX.XXX 001565ca0420\r\nContent-Length: 0\r\n\r\n"

```

**2018-06-06T15:45:33+10:00 WARN Could not find a valid CSeq in packet**

```
2018-06-06T15:45:33+10:00 WARN Could not find a valid CSeq in packet
"NOTIFY sip:102@XXX.XXX.XXX.XXX:5065 SIP/2.0\r\nVia: SIP/2.0/UDP XXX.XXX.XXX.XXX:5060;branch=z9hG4bK-524287-1---c9446e091603ab4f;rport=5060\r\nMax-Forwards: 69\r\nRoute: <sip:3CXSBC@XXX.XXX.XXX.XXX:5060;user=proxy;tnlid=sbc.d89dadae>\r\nContact: <sip:SP1@XXX.XXX.XXX.XXX:5060;tran"

2018-06-06T15:45:33+10:00 WARN Could not find a valid CSeq in packet
"NOTIFY sip:310@XXX.XXX.XXX.XXX:5060 SIP/2.0\r\nVia: SIP/2.0/UDP XXX.XXX.XXX.XXX:5060;branch=z9hG4bK-524287-1---5b81fb5c7f9a030f;rport=5060\r\nMax-Forwards: 69\r\n"
```

**2018-06-06T15:45:54+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLine err: length of s.Val is less than 3. Invalid start line**

```
2018-06-06T15:45:54+10:00 WARN parseStartLine err: received err while parsing start line: parseStartLine err: length of s.Val is less than 3. Invalid start line
"\r\nRoute: <sip:3CXSBC@XXX.XXX.XXX.XXX:5060;user=proxy;tnlid=sbc.d89dadae>\r\nContact: <sip:SP1@XXX.XXX.XXX.XXX:5060;transport=UDP>\r\nTo: \"EMPLOYEE NAME\"<sip:115@SERVER.URL.COM:5060>;tag=4141664961\r\nFrom: <sip:SP1@SERVER.URL.COM:5060>;tag=28917727\r\nCall-ID: 0_402340583@XXX.XXX.XXX.XXX\r\nCSeq: 127 NOTIFY\r\nContent-Type: application/dialog-info+xml\r\nUser-Agent: 3CXPhoneSystem 15.5.10244.4 (10244)\r\nSubscription-State: active;expires=412\r\nEvent: dialog\r\nContent-Length: 910\r\n\r\n<?xml version=\"1.0\"?>\r\n<dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"126\" state=\"full\" entity=\"sip:SP1@XXX.XXX.XXX.XXX:5060\">\r\n<dialog id=\"11426-3548\" call-id=\"-m7fFm_xdPqkhJGsRvmSlQ..\" local-tag=\"75029c54\" remote-tag=\"1352ea6c\" direction=\"recipient\"><state>confirmed</state>\r\n<local><identity>sip:SP1@XXX.XXX.XXX.XXX:5060</identity><target uri=\"sip:SP1@XXX.XXX.XXX.XXX:5060\"/></local><remote><identity>sip:anonymous@XXX.XXX.XXX.XXX:5060</identity><target uri=\"sip:anonymous@XXX.XXX.XXX.XXX:5060\"/></remote></dialog>\r\n<dialog id=\"11428-1194\" call-id=\"XO5RRXdAtJBdcQ3LHqR6MQ..\" local-tag=\"a4a15163\" remote-tag=\"ee5b7447\" direction=\"recipient\"><state>confirmed</state>\r\n<local><identity>sip:SP1@XXX.XXX.XXX.XXX:5060</identity><target uri=\"sip:SP1@XXX.XXX.XXX.XXX:5060\"/></local><remote><identity>sip:114@XXX.XXX.XXX.XXX:5060<"
```

**Comment by negbie** [comment] 2018-06-06 06:53
Nothing special. Some notify without cseq, some malformed startline. Some uncompleted packets.
