### ISSUE TITLE
The DBDropDays parameter doesn't work

### ISSUE THREAD

**Issue by sve71** [sipcapture/heplify-server#350] opened 2020-04-09 12:53 UTC
Hi,

I'm using [the](https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-prom-all) variant (Docker) to capture.
Unfortunately, the DBDROPDAYS parameter doesn't work. I've configured it (on April, 7 at the evening) with the value as shown below
```
- "HEPLIFYSERVER_DBROTATE=true"
- "HEPLIFYSERVER_DBPARTLOG=2h"
- "HEPLIFYSERVER_DBPARTSIP=1h"
- "HEPLIFYSERVER_DBPARTQOS=6h"
- "HEPLIFYSERVER_DBDROPDAYS=1"
#- "HEPLIFYSERVER_DBDROPDAYSCALL=0"
#- "HEPLIFYSERVER_DBDROPDAYSREGISTER=0"
#- "HEPLIFYSERVER_DBDROPDAYSDEFAULT=0"
```

But previous presentations still present and I can find SIP messages that were captured on April 7 and 8. For example:
```
 public | hep_proto_1_registration
 public | hep_proto_1_registration_20200407_2200 | table | root
 public | hep_proto_1_registration_20200407_2300 | table | root
 public | hep_proto_1_registration_20200408_0000 | table | root
 public | hep_proto_1_registration_20200408_0100 | table | root

```
What's wrong?

Thx a lot for your help!

**Comment by lmangani** [comment] 2020-04-09 13:37
Any reason not to use the type rotation here?

```
#- "HEPLIFYSERVER_DBDROPDAYSCALL=0"
#- "HEPLIFYSERVER_DBDROPDAYSREGISTER=0"
#- "HEPLIFYSERVER_DBDROPDAYSDEFAULT=0"
```

**Comment by yannickmcosta** [comment] 2020-04-09 14:01
Can also confirm, I've added

`- "HEPLIFYSERVER_DBDROPDAYS=14"`

to the docker-compose.yml file and, at the time of writing, we can only see up to 2nd April, which is 7 days.

**Comment by sve71** [comment] 2020-04-09 14:38
@lmangani no, I don't have any reason not to use the parms above. From the other hand I thought if there is the common parameter and it's enough to my installation why not to configure just it...
@yannickmcosta thanks for participation. I'm not alone who faced with the issue.

Ok, I'll test dropping tables with the three parms above and give feedback here.

**Comment by lsadehaan** [comment] 2020-04-09 15:08
I have the same problem. I've set mine to: ```- "HEPLIFYSERVER_DBDROPDAYS=1" ```. It doesn't rotate at all. I have also changed ``` - "HEPLIFYSERVER_DBDROPONSTART=true" ``` - and when I restart my container it does indeed rotate correctly. But just on start - not after...
I was also wondering what the settings in the HOMER7 "mapping" interface is for: 
![image](https://user-images.githubusercontent.com/4754900/78910061-be811f80-7a5a-11ea-848b-f5259b952848.png)

I have set the retention here to 1 also just to make sure, but made no difference.

**Comment by lsadehaan** [comment] 2020-04-09 15:09
As a side question/feature request - is it possible to have shorter than 1 day retention? I'd like to keep 12 hours.

**Comment by lmangani** [comment] 2020-04-09 15:16
The more questions you guys mix in a ticket, the less chances it has of being resolved. Mapping and rotation are two different subject i suggest not to confuse.

**Comment by lsadehaan** [comment] 2020-04-09 15:48
I'm sorry, I thought perhaps the "retention" setting was relevant to rotation. It would be sufficient to just say that it is not relevant...

**Comment by lmangani** [comment] 2020-04-09 17:09
>  It would be sufficient to just say that it is not relevant...

It's not relevant

**Comment by sve71** [comment] 2020-04-10 06:39
Hi,

HEPLIFYSERVER_DBDROPDAYSCALL, HEPLIFYSERVER_DBDROPDAYSREGISTER and HEPLIFYSERVER_DBDROPDAYSDEFAULT don't work too. I configured it yesterday and now my docker-compose.yml looks like
```
- "HEPLIFYSERVER_DBROTATE=true"
- "HEPLIFYSERVER_DBPARTLOG=2h"
- "HEPLIFYSERVER_DBPARTSIP=1h"
- "HEPLIFYSERVER_DBPARTQOS=6h"
- "HEPLIFYSERVER_DBDROPDAYS=1"
- "HEPLIFYSERVER_DBDROPDAYSCALL=1"
- "HEPLIFYSERVER_DBDROPDAYSREGISTER=1"
- "HEPLIFYSERVER_DBDROPDAYSDEFAULT=1"
```

The data is able since 9th April.

**Comment by nakchak** [comment] 2020-04-20 12:09
I suspect this is the same root cause as https://github.com/sipcapture/homer7-docker/issues/70#issuecomment-616447821

If the image has pulled in v3 of the cron lib then droptables cron job would silently fail as well as the rotate job

**Comment by negbie** [comment] 2020-04-21 20:01
Should be fixed in latest version. Please do a docker-compose pull

**Closed by negbie** 2020-04-21 20:01 UTC

**Comment by lmangani** [comment] 2020-09-29 11:31
This seems to have resurfaced

**Comment by fuine6** [comment] 2024-10-22 10:36
The problem still exists, can we reopen this?

**Comment by lmangani** [comment] 2024-10-22 10:45
@fuine6 feel free to open a new issue with as many details as possible

**Comment by fuine6** [comment] 2024-10-23 05:42
> @fuine6 feel free to open a new issue with as many details as possible

Sorry, I made a mistake here.

I used
```
HEPLIFYSERVER_DBDropDays
```

Actually it should be
```
HEPLIFYSERVER_DBDROPDAYS
```
